chore(deps): update all non-major dependencies (#15)
[![Mend Renovate](https://app.renovatebot.com/images/banner.svg)](https://renovatebot.com)

This PR contains the following updates:

| Package | Change | Age | Adoption | Passing | Confidence |
|---|---|---|---|---|---|
| [@commitlint/cli](https://commitlint.js.org/) ([source](https://togithub.com/conventional-changelog/commitlint)) | [`^17.4.4` -> `^17.5.1`](https://renovatebot.com/diffs/npm/@commitlint%2fcli/17.4.4/17.5.1) | [![age](https://badges.renovateapi.com/packages/npm/@commitlint%2fcli/17.5.1/age-slim)](https://docs.renovatebot.com/merge-confidence/) | [![adoption](https://badges.renovateapi.com/packages/npm/@commitlint%2fcli/17.5.1/adoption-slim)](https://docs.renovatebot.com/merge-confidence/) | [![passing](https://badges.renovateapi.com/packages/npm/@commitlint%2fcli/17.5.1/compatibility-slim/17.4.4)](https://docs.renovatebot.com/merge-confidence/) | [![confidence](https://badges.renovateapi.com/packages/npm/@commitlint%2fcli/17.5.1/confidence-slim/17.4.4)](https://docs.renovatebot.com/merge-confidence/) |
| [@mheob/eslint-config](https://togithub.com/mheob/config/tree/main/packages/eslint-config) ([source](https://togithub.com/mheob/config)) | [`^4.2.0` -> `^4.2.1`](https://renovatebot.com/diffs/npm/@mheob%2feslint-config/4.2.0/4.2.1) | [![age](https://badges.renovateapi.com/packages/npm/@mheob%2feslint-config/4.2.1/age-slim)](https://docs.renovatebot.com/merge-confidence/) | [![adoption](https://badges.renovateapi.com/packages/npm/@mheob%2feslint-config/4.2.1/adoption-slim)](https://docs.renovatebot.com/merge-confidence/) | [![passing](https://badges.renovateapi.com/packages/npm/@mheob%2feslint-config/4.2.1/compatibility-slim/4.2.0)](https://docs.renovatebot.com/merge-confidence/) | [![confidence](https://badges.renovateapi.com/packages/npm/@mheob%2feslint-config/4.2.1/confidence-slim/4.2.0)](https://docs.renovatebot.com/merge-confidence/) |
| [@types/node](https://togithub.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/node) ([source](https://togithub.com/DefinitelyTyped/DefinitelyTyped)) | [`^18.15.0` -> `^18.15.11`](https://renovatebot.com/diffs/npm/@types%2fnode/18.15.0/18.15.11) | [![age](https://badges.renovateapi.com/packages/npm/@types%2fnode/18.15.11/age-slim)](https://docs.renovatebot.com/merge-confidence/) | [![adoption](https://badges.renovateapi.com/packages/npm/@types%2fnode/18.15.11/adoption-slim)](https://docs.renovatebot.com/merge-confidence/) | [![passing](https://badges.renovateapi.com/packages/npm/@types%2fnode/18.15.11/compatibility-slim/18.15.0)](https://docs.renovatebot.com/merge-confidence/) | [![confidence](https://badges.renovateapi.com/packages/npm/@types%2fnode/18.15.11/confidence-slim/18.15.0)](https://docs.renovatebot.com/merge-confidence/) |
| [eslint](https://eslint.org) ([source](https://togithub.com/eslint/eslint)) | [`^8.36.0` -> `^8.37.0`](https://renovatebot.com/diffs/npm/eslint/8.36.0/8.37.0) | [![age](https://badges.renovateapi.com/packages/npm/eslint/8.37.0/age-slim)](https://docs.renovatebot.com/merge-confidence/) | [![adoption](https://badges.renovateapi.com/packages/npm/eslint/8.37.0/adoption-slim)](https://docs.renovatebot.com/merge-confidence/) | [![passing](https://badges.renovateapi.com/packages/npm/eslint/8.37.0/compatibility-slim/8.36.0)](https://docs.renovatebot.com/merge-confidence/) | [![confidence](https://badges.renovateapi.com/packages/npm/eslint/8.37.0/confidence-slim/8.36.0)](https://docs.renovatebot.com/merge-confidence/) |
| [prettier](https://prettier.io) ([source](https://togithub.com/prettier/prettier)) | [`^2.8.4` -> `^2.8.7`](https://renovatebot.com/diffs/npm/prettier/2.8.4/2.8.7) | [![age](https://badges.renovateapi.com/packages/npm/prettier/2.8.7/age-slim)](https://docs.renovatebot.com/merge-confidence/) | [![adoption](https://badges.renovateapi.com/packages/npm/prettier/2.8.7/adoption-slim)](https://docs.renovatebot.com/merge-confidence/) | [![passing](https://badges.renovateapi.com/packages/npm/prettier/2.8.7/compatibility-slim/2.8.4)](https://docs.renovatebot.com/merge-confidence/) | [![confidence](https://badges.renovateapi.com/packages/npm/prettier/2.8.7/confidence-slim/2.8.4)](https://docs.renovatebot.com/merge-confidence/) |
| [tsup](https://tsup.egoist.dev/) ([source](https://togithub.com/egoist/tsup)) | [`^6.6.3` -> `^6.7.0`](https://renovatebot.com/diffs/npm/tsup/6.6.3/6.7.0) | [![age](https://badges.renovateapi.com/packages/npm/tsup/6.7.0/age-slim)](https://docs.renovatebot.com/merge-confidence/) | [![adoption](https://badges.renovateapi.com/packages/npm/tsup/6.7.0/adoption-slim)](https://docs.renovatebot.com/merge-confidence/) | [![passing](https://badges.renovateapi.com/packages/npm/tsup/6.7.0/compatibility-slim/6.6.3)](https://docs.renovatebot.com/merge-confidence/) | [![confidence](https://badges.renovateapi.com/packages/npm/tsup/6.7.0/confidence-slim/6.6.3)](https://docs.renovatebot.com/merge-confidence/) |

---

### Release Notes

<details>
<summary>conventional-changelog/commitlint</summary>

### [`v17.5.1`](https://togithub.com/conventional-changelog/commitlint/blob/HEAD/@&#8203;commitlint/cli/CHANGELOG.md#&#8203;1751-httpsgithubcomconventional-changelogcommitlintcomparev1750v1751-2023-03-28)

[Compare Source](https://togithub.com/conventional-changelog/commitlint/compare/v17.5.0...v17.5.1)

**Note:** Version bump only for package [@&#8203;commitlint/cli](https://togithub.com/commitlint/cli)

### [`v17.5.0`](https://togithub.com/conventional-changelog/commitlint/blob/HEAD/@&#8203;commitlint/cli/CHANGELOG.md#&#8203;1750-httpsgithubcomconventional-changelogcommitlintcomparev1744v1750-2023-03-22)

[Compare Source](https://togithub.com/conventional-changelog/commitlint/compare/v17.4.4...v17.5.0)

**Note:** Version bump only for package [@&#8203;commitlint/cli](https://togithub.com/commitlint/cli)

#### [17.4.4](https://togithub.com/conventional-changelog/commitlint/compare/v17.4.3...v17.4.4) (2023-02-17)

**Note:** Version bump only for package [@&#8203;commitlint/cli](https://togithub.com/commitlint/cli)

#### [17.4.3](https://togithub.com/conventional-changelog/commitlint/compare/v17.4.2...v17.4.3) (2023-02-13)

**Note:** Version bump only for package [@&#8203;commitlint/cli](https://togithub.com/commitlint/cli)

#### [17.4.2](https://togithub.com/conventional-changelog/commitlint/compare/v17.4.1...v17.4.2) (2023-01-12)

**Note:** Version bump only for package [@&#8203;commitlint/cli](https://togithub.com/commitlint/cli)

#### [17.4.1](https://togithub.com/conventional-changelog/commitlint/compare/v17.4.0...v17.4.1) (2023-01-09)

**Note:** Version bump only for package [@&#8203;commitlint/cli](https://togithub.com/commitlint/cli)

</details>

<details>
<summary>mheob/config</summary>

### [`v4.2.1`](https://togithub.com/mheob/config/releases/tag/%40mheob/eslint-config%404.2.1)

[Compare Source](https://togithub.com/mheob/config/compare/@mheob/eslint-config@4.2.0...@mheob/eslint-config@4.2.1)

##### Patch Changes

-   update dependencies --> ([#&#8203;121](https://togithub.com/mheob/config/pull/121)) by
    [@&#8203;mheob](https://togithub.com/mheob)

</details>

<details>
<summary>eslint/eslint</summary>

### [`v8.37.0`](https://togithub.com/eslint/eslint/releases/tag/v8.37.0)

[Compare Source](https://togithub.com/eslint/eslint/compare/v8.36.0...v8.37.0)

#### Features

-   [`b6ab8b2`](https://togithub.com/eslint/eslint/commit/b6ab8b2a2ca8807baca121407f5bfb0a0a839427) feat: `require-unicode-regexp` add suggestions ([#&#8203;17007](https://togithub.com/eslint/eslint/issues/17007)) (Josh Goldberg)
-   [`10022b1`](https://togithub.com/eslint/eslint/commit/10022b1f4bda1ad89193512ecf18c2ee61db8202) feat: Copy getScope() to SourceCode ([#&#8203;17004](https://togithub.com/eslint/eslint/issues/17004)) (Nicholas C. Zakas)
-   [`1665c02`](https://togithub.com/eslint/eslint/commit/1665c029acb92bf8812267f1647ad1a7054cbcb4) feat: Use plugin metadata for flat config serialization ([#&#8203;16992](https://togithub.com/eslint/eslint/issues/16992)) (Nicholas C. Zakas)
-   [`b3634f6`](https://togithub.com/eslint/eslint/commit/b3634f695ddab6a82c0a9b1d8695e62b60d23366) feat: docs license ([#&#8203;17010](https://togithub.com/eslint/eslint/issues/17010)) (Samuel Roldan)
-   [`892e6e5`](https://togithub.com/eslint/eslint/commit/892e6e58c5a07a549d3104de3b6b5879797dc97f) feat: languageOptions.parser must be an object. ([#&#8203;16985](https://togithub.com/eslint/eslint/issues/16985)) (Nicholas C. Zakas)

#### Bug Fixes

-   [`619f3fd`](https://togithub.com/eslint/eslint/commit/619f3fd17324c7b71bf17e02047d0c6dc7e5109e) fix: correctly handle `null` default config in `RuleTester` ([#&#8203;17023](https://togithub.com/eslint/eslint/issues/17023)) (Brad Zacher)
-   [`1fbf118`](https://togithub.com/eslint/eslint/commit/1fbf1184fed57df02640aad4659afb54dc26a2e9) fix: `getFirstToken`/`getLastToken` on comment-only node ([#&#8203;16889](https://togithub.com/eslint/eslint/issues/16889)) (Francesco Trotta)
-   [`129e252`](https://togithub.com/eslint/eslint/commit/129e252132c7c476d7de17f40b54a333ddb2e6bb) fix: Fix typo in `logical-assignment-operators` rule description ([#&#8203;17000](https://togithub.com/eslint/eslint/issues/17000)) (Francesco Trotta)

#### Documentation

-   [`75339df`](https://togithub.com/eslint/eslint/commit/75339df99418df4d7e05a77e42ed7e22eabcc9e0) docs: fix typos and missing info in id-match docs ([#&#8203;17029](https://togithub.com/eslint/eslint/issues/17029)) (Ed Lucas)
-   [`ec2d830`](https://togithub.com/eslint/eslint/commit/ec2d8307850dd039e118c001416606e1e0342bc8) docs: Fix typos in the `semi` rule docs ([#&#8203;17012](https://togithub.com/eslint/eslint/issues/17012)) (Andrii Lundiak)
-   [`e39f28d`](https://togithub.com/eslint/eslint/commit/e39f28d8578a00f4da8d4ddad559547950128a0d) docs: add back to top button ([#&#8203;16979](https://togithub.com/eslint/eslint/issues/16979)) (Tanuj Kanti)
-   [`721c717`](https://togithub.com/eslint/eslint/commit/721c71782a7c11025689a1500e7690fb3794fcce) docs: Custom Processors cleanup and expansion ([#&#8203;16838](https://togithub.com/eslint/eslint/issues/16838)) (Ben Perlmutter)
-   [`d049f97`](https://togithub.com/eslint/eslint/commit/d049f974103e530ef76ede25af701635caf1f405) docs: 'How ESLint is Maintained' page ([#&#8203;16961](https://togithub.com/eslint/eslint/issues/16961)) (Ben Perlmutter)
-   [`5251a92`](https://togithub.com/eslint/eslint/commit/5251a921866e8d3b380dfe8db8a6e6ab97773d5e) docs: Describe guard options for guard-for-in ([#&#8203;16986](https://togithub.com/eslint/eslint/issues/16986)) (alope107)
-   [`6157d81`](https://togithub.com/eslint/eslint/commit/6157d813e19b80481a46f8cbdf9eae18a55e5619) docs: Add example to guard-for-in docs. ([#&#8203;16983](https://togithub.com/eslint/eslint/issues/16983)) (alope107)
-   [`fd47998`](https://togithub.com/eslint/eslint/commit/fd47998af6efadcdf5ba93e0bd1f4c02d97d22b3) docs: update `Array.prototype.toSorted` specification link ([#&#8203;16982](https://togithub.com/eslint/eslint/issues/16982)) (Milos Djermanovic)
-   [`3e1cf6b`](https://togithub.com/eslint/eslint/commit/3e1cf6bfc5ebc29314ddbe462d6cb580e9ab085c) docs: Copy edits on Maintain ESLint docs ([#&#8203;16939](https://togithub.com/eslint/eslint/issues/16939)) (Ben Perlmutter)

#### Chores

-   [`c67f299`](https://togithub.com/eslint/eslint/commit/c67f2992a743de4765bb6f11c12622e3651324b9) chore: upgrade [@&#8203;eslint/js](https://togithub.com/eslint/js)[@&#8203;8](https://togithub.com/8).37.0 ([#&#8203;17033](https://togithub.com/eslint/eslint/issues/17033)) (Milos Djermanovic)
-   [`ee9ddbd`](https://togithub.com/eslint/eslint/commit/ee9ddbd63e262aed0052853760866c7a054af561) chore: package.json update for [@&#8203;eslint/js](https://togithub.com/eslint/js) release (ESLint Jenkins)
-   [`dddb475`](https://togithub.com/eslint/eslint/commit/dddb47528816cd7e2e737bfde108ed4d62e6a219) chore: upgrade [@&#8203;eslint/eslintrc](https://togithub.com/eslint/eslintrc)[@&#8203;2](https://togithub.com/2).0.2 ([#&#8203;17032](https://togithub.com/eslint/eslint/issues/17032)) (Milos Djermanovic)
-   [`522431e`](https://togithub.com/eslint/eslint/commit/522431e5206bac2fcb41c0d6dc98a84929203bee) chore: upgrade espree@9.5.1 ([#&#8203;17031](https://togithub.com/eslint/eslint/issues/17031)) (Milos Djermanovic)
-   [`f5f9a88`](https://togithub.com/eslint/eslint/commit/f5f9a88c79b32222c0331a9bac1c02571d953b69) chore: upgrade eslint-visitor-keys@3.4.0 ([#&#8203;17030](https://togithub.com/eslint/eslint/issues/17030)) (Milos Djermanovic)
-   [`4dd8d52`](https://togithub.com/eslint/eslint/commit/4dd8d524e0fc9e8e2019df13f8b968021600e85c) ci: bump actions/stale from 7 to 8 ([#&#8203;17026](https://togithub.com/eslint/eslint/issues/17026)) (dependabot\[bot])
-   [`ad9dd6a`](https://togithub.com/eslint/eslint/commit/ad9dd6a933fd098a0d99c6a9aa059850535c23ee) chore: remove duplicate scss, ([#&#8203;17005](https://togithub.com/eslint/eslint/issues/17005)) (Strek)
-   [`ada6a3e`](https://togithub.com/eslint/eslint/commit/ada6a3e6e3607523958f35e1260537630ec0e976) ci: unpin Node 19 ([#&#8203;16993](https://togithub.com/eslint/eslint/issues/16993)) (Milos Djermanovic)
-   [`c3da975`](https://togithub.com/eslint/eslint/commit/c3da975e69fde46f35338ce48528841a8dc1ffd2) chore: Remove triage label from template ([#&#8203;16990](https://togithub.com/eslint/eslint/issues/16990)) (Nicholas C. Zakas)
-   [`69bc0e2`](https://togithub.com/eslint/eslint/commit/69bc0e2f4412998f9384600a100d7882ea4dd3f3) ci: pin Node 19 to 19.7.0 ([#&#8203;16987](https://togithub.com/eslint/eslint/issues/16987)) (Milos Djermanovic)

</details>

<details>
<summary>prettier/prettier</summary>

### [`v2.8.7`](https://togithub.com/prettier/prettier/blob/HEAD/CHANGELOG.md#&#8203;287)

[Compare Source](https://togithub.com/prettier/prettier/compare/2.8.6...2.8.7)

[diff](https://togithub.com/prettier/prettier/compare/2.8.6...2.8.7)

##### Allow multiple decorators on same getter/setter ([#&#8203;14584](https://togithub.com/prettier/prettier/pull/14584) by [@&#8203;fisker](https://togithub.com/fisker))



```ts
// Input
class A {
  @&#8203;decorator()
  get foo () {}
  
  @&#8203;decorator()
  set foo (value) {}
}

// Prettier 2.8.6
SyntaxError: Decorators cannot be applied to multiple get/set accessors of the same name. (5:3)
  3 |   get foo () {}
  4 |   
> 5 |   @&#8203;decorator()
    |   ^^^^^^^^^^^^
  6 |   set foo (value) {}
  7 | }

// Prettier 2.8.7
class A {
  @&#8203;decorator()
  get foo() {}

  @&#8203;decorator()
  set foo(value) {}
}
```

### [`v2.8.6`](https://togithub.com/prettier/prettier/blob/HEAD/CHANGELOG.md#&#8203;286)

[Compare Source](https://togithub.com/prettier/prettier/compare/2.8.5...2.8.6)

[diff](https://togithub.com/prettier/prettier/compare/2.8.5...2.8.6)

##### Allow decorators on private members and class expressions ([#&#8203;14548](https://togithub.com/prettier/prettier/pull/14548) by [@&#8203;fisker](https://togithub.com/fisker))



```ts
// Input
class A {
  @&#8203;decorator()
  #privateMethod () {}
}

// Prettier 2.8.5
SyntaxError: Decorators are not valid here. (2:3)
  1 | class A {
> 2 |   @&#8203;decorator()
    |   ^^^^^^^^^^^^
  3 |   #privateMethod () {}
  4 | }

// Prettier 2.8.6
class A {
  @&#8203;decorator()
  #privateMethod() {}
}
```

### [`v2.8.5`](https://togithub.com/prettier/prettier/blob/HEAD/CHANGELOG.md#&#8203;285)

[Compare Source](https://togithub.com/prettier/prettier/compare/2.8.4...2.8.5)

[diff](https://togithub.com/prettier/prettier/compare/2.8.4...2.8.5)

##### Support TypeScript 5.0 ([#&#8203;14391](https://togithub.com/prettier/prettier/pull/14391) by [@&#8203;fisker](https://togithub.com/fisker), [#&#8203;13819](https://togithub.com/prettier/prettier/pull/13819) by [@&#8203;fisker](https://togithub.com/fisker), [@&#8203;sosukesuzuki](https://togithub.com/sosukesuzuki))

TypeScript 5.0 introduces two new syntactic features:

-   `const` modifiers for type parameters
-   `export type *` declarations

##### Add missing parentheses for decorator ([#&#8203;14393](https://togithub.com/prettier/prettier/pull/14393) by [@&#8203;fisker](https://togithub.com/fisker))



```jsx
// Input
class Person {
  @&#8203;(myDecoratorArray[0])
  greet() {}
}

// Prettier 2.8.4
class Person {
  @&#8203;myDecoratorArray[0]
  greet() {}
}

// Prettier 2.8.5
class Person {
  @&#8203;(myDecoratorArray[0])
  greet() {}
}
```

##### Add parentheses for `TypeofTypeAnnotation` to improve readability ([#&#8203;14458](https://togithub.com/prettier/prettier/pull/14458) by [@&#8203;fisker](https://togithub.com/fisker))



```tsx
// Input
type A = (typeof node.children)[];

// Prettier 2.8.4
type A = typeof node.children[];

// Prettier 2.8.5
type A = (typeof node.children)[];
```

##### Support `max_line_length=off` when parsing `.editorconfig` ([#&#8203;14516](https://togithub.com/prettier/prettier/pull/14516) by [@&#8203;josephfrazier](https://togithub.com/josephfrazier))

If an .editorconfig file is in your project and it sets `max_line_length=off` for the file you're formatting,
it will be interpreted as a `printWidth` of `Infinity` rather than being ignored
(which previously resulted in the default `printWidth` of 80 being applied, if not overridden by Prettier-specific configuration).



```html
<!-- Input -->
<div className='HelloWorld' title={`You are visitor number ${ num }`} onMouseOver={onMouseOver}/>

<!-- Prettier 2.8.4 -->
<div
  className="HelloWorld"
  title={`You are visitor number ${num}`}
  onMouseOver={onMouseOver}
/>;

<!-- Prettier 2.8.5 -->
<div className="HelloWorld" title={`You are visitor number ${num}`} onMouseOver={onMouseOver} />;
```

</details>

<details>
<summary>egoist/tsup</summary>

### [`v6.7.0`](https://togithub.com/egoist/tsup/releases/tag/v6.7.0)

[Compare Source](https://togithub.com/egoist/tsup/compare/v6.6.3...v6.7.0)

##### Features

-   add function type for options.injectStyle ([#&#8203;855](https://togithub.com/egoist/tsup/issues/855)) ([01169b3](https://togithub.com/egoist/tsup/commit/01169b39756a26d84bd393e0f4c4a0c3bec922ca))
-   support typescript 5.0 ([#&#8203;859](https://togithub.com/egoist/tsup/issues/859)) ([3e15867](https://togithub.com/egoist/tsup/commit/3e158674bdeb3d060404987e1b278fd7d21ccda1))

</details>

---

### Configuration

📅 **Schedule**: Branch creation - "before 4am on Monday" in timezone Europe/Berlin, Automerge - At any time (no schedule defined).

🚦 **Automerge**: Disabled by config. Please merge this manually once you are satisfied.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the rebase/retry checkbox.

👻 **Immortal**: This PR will be recreated if closed unmerged. Get [config help](https://togithub.com/renovatebot/renovate/discussions) if that's undesired.

---

 - [ ] If you want to rebase/retry this PR, check this box

---

This PR has been generated by [Mend Renovate](https://www.mend.io/free-developer-tools/renovate/). View repository job log [here](https://app.renovatebot.com/dashboard#github/mheob/used-pm).